// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated file: added minimal part-of directive to satisfy analyzer

part of 'providers.dart';

// If this file is actually generated by build_runner (riverpod/freezed/json_serializable),
// the generator will overwrite this file. The part-of directive should match the
// parent file that contains `part 'providers.g.dart';`.
