// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNdPAsAQ-ESh5DJ7Twhjxv5uShWSQHpM',
    appId: '1:206115897603:web:ef9cbdaa462de1c8ed6936',
    messagingSenderId: '206115897603',
    projectId: 'bazaar-01-4e57f',
    authDomain: 'bazaar-01-4e57f.firebaseapp.com',
    storageBucket: 'bazaar-01-4e57f.firebasestorage.app',
    measurementId: 'G-WD0B1C7KYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNXpbPwNI_E6rruduYMdskAjAYqH0Z1c',
    appId: '1:206115897603:android:1f5a5fbe08e76132ed6936',
    messagingSenderId: '206115897603',
    projectId: 'bazaar-01-4e57f',
    storageBucket: 'bazaar-01-4e57f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2uSQzfjbfSUpxzTMfpkryPgCc4HLHBIU',
    appId: '1:206115897603:ios:1b956368f233d367ed6936',
    messagingSenderId: '206115897603',
    projectId: 'bazaar-01-4e57f',
    storageBucket: 'bazaar-01-4e57f.firebasestorage.app',
    iosClientId: '206115897603-j3hei2ur2pk0v0ota3sk2om68b9mmmnd.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}